### PR TITLE
3. Cone as gfx element class

### PR DESCRIPTION
**Pull request by shazz**
@salem-ok, on this branch `gfx_cone`, I tried to externalize one graphical element, the cones, as its one entity. That could be an example for any other obstacle.
This branch is build upon the `sample_manager` branch, to better to accept the previous PR first even if merging should work well.

To test it, change in `pysprint_tracks.py` to get some cones in the first round:
````python
    def init_obstacles(self, race_counter):
        #Determine the number of obstacles
        nb_obstacles = 0
        min_obstacles = 0
        max_obstacles = 0
        nb_cones_max = 0 # => to 10
````

**Content**
 - in `gfx/`, `Cone` is defined in the file `cone.py`
 - tracks' `self.traffic_cones` is now a list of `Cone` and to be displayed, only call `cone.blit()`

**TODO**
I did not understand yet how `get_random_position()` works and its dependencies so the cones positions are initialized when displayed:

````python
        #Display Traffic Cones
        if race_started:
            for cone in self.traffic_cones:

                # should be done before
                if cone.pos is None:
                    cone.update(self.get_random_position(traffic_cone.get_height(), traffic_cone_shade.get_width()))

                cone.blit()
````

That's **pretty bad** :) the `cone.update()` should happen when the track is initialized not when blitting.

### CODE REVIEW

**Comment by salem-ok** [comment]
@shazz since this PR builds on Sample manager, I'll review it once we have resolved the sample manager issue if that's OK?

**Comment by salem-ok** [comment]
Same as the spills, my changes generate some conflicts. Looks like you need to add a new member to your object class so we know whether it's place on a bridge or a ramp to blit it correctly:
` self.on_bridge_or_ramp_grease_traffic_cones = None`

**Comment by shazz** [comment]
Basically I added that:
````python
                    pos, on_object = self.get_random_position(traffic_cone.get_height(), traffic_cone_shade.get_width())
                    cone.update(pos) if not on_object else cone.disable()
````

So if it is on an object, the spill is disabled. It is what is expected ?

**Review by salem-ok — APPROVED** [review]
Works fine on Linux, Windows & Raspberry Pi

**Comment by salem-ok** [comment]
> Basically I added that:
> 
> ```python
> pos, on_object = self.get_random_position(traffic_cone.get_height(), traffic_cone_shade.get_width())
> cone.update(pos) if not on_object else cone.disable()
> ```
> 
> So if it is on an object, the spill is disabled. It is what is expected ?

For the cones, yes they disappear after being hit once. but not for spills.

The new boolean I added was to blit correctly objects on bridges. It works fine in your branch. Happy to merge!

**Pull request merged**
