### PR TITLE
Move control_methods to its own module

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Review by salem-ok — APPROVED** [review]

**Comment by salem-ok** [comment]
@elfosardo 
The main file was not properly refactored. I have reverted back these changes.

**Comment by elfosardo** [comment]
@salem-ok hi! Sorry to read that, will you be more specific on what was wrong so I can fix it and repropose it?

**Comment by salem-ok** [comment]
sure @elfosardo the main module pysprint.py could not load the control methods and the game would not start.

I've invited you you can now create a new PR form the main branch and test do some minimal smoke tests (test that the game starts and runs) and minimal regression tests on what you changed i.e.  test that the controls work as expected with keyboard and Joystick/Gamepad. There is no continuous integration or unit tests at this point, se we have to manually test the code.

**Comment by elfosardo** [comment]
@salem-ok thanks! Alright, I'll look back into that :)

**Pull request merged**
