### PR TITLE
1. Remove hardcoded json tracks

### PR DESCRIPTION
**Pull request by shazz**
@salem-ok , in this branch there is a very little patch to avoid hardcoding the json tracks filenames. Now, it just reads all the json files in `Assets/tracks`. Like that, it should be easier to add new custom tracks.

**Content**
 - in the file `pysprint/py`, the function `initialize_tracks()` was simplified and hardcoded filenames were removed from `pysprint_tracks.py`

**TODO**
 - use `jsonschema` library to validate the json file schema

### CODE REVIEW

**Comment by salem-ok** [comment]
@shazz thanks for this, it was itching me to do something like that, I really appreciate.

It works almost perfectly, including on the Pi.

There is just a strange behaviour:

- On windows when you start a game the track selection menu opens with Track 1 (as expected)
- On my Unbuntu box (21.04), the track selection menu opens with Track 2
- On my Raspberry Pi 4, the track selection menu opens with Track 8

It is always the same track selected by default, regardless of which car you start playing with, but varies on the OS...

If you can fix that I'm more than happy to merge, once again this is an awesome improvement!

**Comment by salem-ok** [comment]
Maybe just forcing a sorting of the files when you fetch them from the new folder?

**Comment by shazz** [comment]
In fact I did not check but I expected you were using the `track_number` attribute in the json file to select the track and you were not relying on the list order :)

Ok I'll patch the code to do that.

**Comment by shazz** [comment]
Can you give a try now ?

**Comment by salem-ok** [comment]
All Good, thanks! And yes - when there's a "clean" way and a "lazy" way to do things, you can safely assume that I have been lazy :)

**Review by salem-ok — COMMENTED** [review]
Thanks!!

**Pull request merged**
