### PR TITLE
2. Added sample manager

### PR DESCRIPTION
**Pull request by shazz**
Hey @salem-ok , I added the sample manager in a branch, here is the pull request, you can review it, possibly test the code :) then merge it and delete the branch and close the PR.

**Content**
Removed direct deps to pygame mixer and added a Sample Manager class.

The code now instantiates 2 sample managers, one for the SFX and one for the Music.
Each manager reads a configuration file to associate the samples to wav files. Like that, multiple sound configurations can be supported if people want to add their sounds :)
The Sample Manager class doesn't feature all capabilities of pygame mixer but methods could be added. I only added what you were actually using.

Also added a `requirements.txt` file used to create a virtualenv:
````
# install virtualenv if not yet added
pip install virtualenv # or sudo apt-get install python3-virtualenv on Ubuntu

# create a virtual environment with python 3.8 (required on your path)
virtualenv --python=3.8 .venv

# activate the virtualenv
source .venv/bin/activate  # or /Scripts/Activate on windows

# install the pysprint deps into the venv
pip install -r requirements.txt

# check !
python --version
pip freeze
````

**Unit tests**
Pytest tests are added for the Sample Manager:
````
pytest tests
````

**Assets / organization**

 - Samples (wav) and configurations are moved to `Assets/sound/`
 - `.gitignore` modified to ignore pycache
 - pycache versioned files deleted

**Dependencies**
- `pytest` for unit testing
- `loguru` to manage logs, better than `print` :)

### CODE REVIEW

**Comment by shazz** [comment]
I found the Arcade version music and SFX, I'll add a json file with them  ;)
https://www.youtube.com/watch?v=APrQ6V0fR9E

**Comment by salem-ok** [comment]
@shazz I've tested this PR, I was relieved you created it from yesterday's latest commits I made:)

Great improvement!
It runs  perfectly on Windows I love the logging tool, and how all played samples are dutifully logged in color:)

However, I have errors on Raspberry Pi 4:

`pi@raspberrypivault:~/coding/PR/PySprint $ python3 pysprint.py 
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "pysprint.py", line 27, in <module>
    SampleManager.create_manager("sfx", "Assets/sound/smp_sfx.json")
  File "/home/pi/coding/PR/PySprint/managers/sample_manager.py", line 38, in create_manager
    mgr = cls(configuration_path)
  File "/home/pi/coding/PR/PySprint/managers/sample_manager.py", line 70, in __init__
    self.samples[name] = Sample(Path(path))
  File "/home/pi/coding/PR/PySprint/managers/sample_manager.py", line 16, in __init__
    self.sound = pygame.mixer.Sound(path)
TypeError: Unrecognized argument (type PosixPath)
`
- It required pathlib to be installed (not listed in your requirements.txt, not sure if it needs to be added)
I still get the same error after installing pathlib.
- Note: The Pi has old libraries installed by default:
- Python 3.7.3 installed by default (not 3.8 or more recent). 
- Pygame 1.9.4
Upgrading pygame is easy enough with pip, but pygame 2.0+ has performance issues on the Pi (I opened an issue on it yesterday).
Upgrade python on the Pi is kind of a pain, you need to build your own so I'd rather stick to backwards compatibility with Python 3.7 and Pygame 1.9.4, So it's easy to just pull the code and run for anybody using a Pi.

Could you please have a look a this error on the Pi? Happy to test if you don't have the right environment.

**Comment by shazz** [comment]
hum this is weird. `pathlib` is included in the Python library since 3.4... especially to avoid those Windows / Linux paths issues.
Can you try this version and tell me ?

Else I'll try to find a RPi somewhere (I have some, just need some setup)

**Review by salem-ok — APPROVED** [review]
It works on the Pi! Thanks!!

To be noted, logging with your log library doesn't seem impact the performance of the game. When I debug with my flags using just print() it cripples the poor Raspberry pi...

**Comment by salem-ok** [comment]
Small conflict on the imports in the main file I think I figured out how to solve it. By now you'll have guessed I am a total noob at collaborating on GitHub, I barely grasp what a pull request is. When I stopped coding professionally, the best tool around was SVN :)

**Pull request merged**
